export const menuThemeMap = {
  trainingPuzzle: {
    titleKey: 'home.trainingPuzzle',
    background: 'sub_color/indigo/bg',
    iconColor: 'main_color/blue_p',
    iconName: 'TrainingIcon',
    route: 'TrainingPacks',
  },
  communityPuzzle: {
    titleKey: 'home.communityPuzzle',
    background: 'sub_color/orange/bg',
    iconColor: 'main_color/yellow_s',
    iconName: 'CommunityIcon',
    route: 'CommunityPuzzles',
  },
  rankingPuzzle: {
    titleKey: 'home.rankingPuzzle',
    background: 'sub_color/yellow/bg',
    iconColor: 'main_color/yellow_p',
    iconName: 'LightningIcon',
    route: 'RankedPuzzleSolve',
  },
  trainingPuzzleReview: {
    titleKey: 'puzzle.review',
    background: 'sub_color/indigo/bg',
    iconColor: 'main_color/blue_p',
    iconName: 'TrainingIcon',
    route: 'TrainingPuzzleReview',
  },
  communityPuzzleReview: {
    titleKey: 'puzzle.review',
    background: 'sub_color/orange/bg',
    iconColor: 'main_color/yellow_s',
    iconName: 'CommunityIcon',
    route: 'CommunityPuzzleReview',
  },
  trainingPuzzleViewAnswer: {
    titleKey: 'puzzle.viewAnswer',
    background: 'sub_color/indigo/bg',
    iconColor: 'main_color/blue_p',
    iconName: 'TrainingIcon',
    route: 'TrainingPuzzleReview',
  },
  communityPuzzleViewAnswer: {
    titleKey: 'puzzle.viewAnswer',
    background: 'sub_color/orange/bg',
    iconColor: 'main_color/yellow_s',
    iconName: 'CommunityIcon',
    route: 'CommunityPuzzleReview',
  },
  ranking: {
    titleKey: 'common.ranking',
    background: 'sub_color/green/bg',
    iconColor: 'sub_color/green/p',
    iconName: 'RankingIcon',
    route: 'Ranking',
  },
  myPuzzle: {
    titleKey: 'common.myPuzzle',
    background: 'sub_color/beige/bg',
    iconColor: 'sub_color/beige/p',
    iconName: 'ArchiveIcon',
    route: 'MyPuzzles',
  },
  likes: {
    titleKey: 'common.likes',
    background: 'sub_color/red/bg',
    iconColor: 'sub_color/red/p',
    iconName: 'HeartMediumIcon',
    route: 'LikedPuzzles',
  },
  notice: {
    titleKey: 'common.notice',
    background: 'sub_color/blue/bg',
    iconColor: 'sub_color/blue/p',
    iconName: 'NoticeIcon',
    route: 'Home',
  },
  settings: {
    titleKey: 'common.settings',
    background: 'gray/gray100',
    iconColor: 'gray/gray400',
    iconName: 'SettingIcon',
    route: 'Settings',
  },
  language: {
    titleKey: 'settings.language',
    background: 'gray/gray100',
    iconColor: 'gray/gray400',
    iconName: 'SettingIcon',
    route: 'Language',
  },
  changeNickname: {
    titleKey: 'settings.changeNickname',
    background: 'gray/gray100',
    iconColor: 'gray/gray400',
    iconName: 'SettingIcon',
    route: 'ChangeNickname',
  },
  signup: {
    titleKey: 'auth.signup',
    background: 'sub_color/indigo/bg',
    iconColor: 'main_color/blue_p',
    iconName: 'LogoIcon',
    route: null,
  },
  home: {
    titleKey: 'common.appName',
    background: 'sub_color/indigo/bg',
    iconColor: 'main_color/blue_p',
    iconName: 'LogoIcon',
    route: null,
  },
} as const;

export type MenuType = keyof typeof menuThemeMap;

export const headerMenuTypeMap = {
  Home: 'home',
  Signup: 'signup',
  MyPuzzles: 'myPuzzle',
  LikedPuzzles: 'likes',
  Ranking: 'ranking',
  Settings: 'settings',
  Language: 'language',
  ChangeNickname: 'changeNickname',
  TrainingPacks: 'trainingPuzzle',
  TrainingPuzzles: 'trainingPuzzle',
  TrainingPuzzleSolve: 'trainingPuzzle',
  TrainingPuzzleReview: 'trainingPuzzleReview',
  TrainingPuzzleViewAnswer: 'trainingPuzzleViewAnswer',
  CommunityPuzzles: 'communityPuzzle',
  CommunityPuzzleSolve: 'communityPuzzle',
  CommunityPuzzleReview: 'communityPuzzleReview',
  CommunityPuzzleViewAnswer: 'communityPuzzleViewAnswer',
  CreateCommunityPuzzle: 'communityPuzzle',
  AnswerCommunityPuzzle: 'communityPuzzle',
  RankedPuzzleSolve: 'rankingPuzzle',
} as const satisfies Record<string, MenuType>;

export const getMenuTypeByRouteName = (routeName: string): MenuType | undefined =>
  headerMenuTypeMap[routeName as keyof typeof headerMenuTypeMap];
